### ISSUE TITLE
~6.1 is not installable, sass compilation breaks

### ISSUE THREAD

**Issue by steadweb** [jadu/pulsar#223]
`~6.2` I believe, has fixed this. Possibly requires a back port.

```
[31m>> [39mError: ".block-list--bordered" failed to @extend ".block-list--padded".[31m
>> [39m       The selector ".block-list--padded" was not found.[31m
>> [39m       Use "@extend .block-list--padded !optional" if the extend should be able to fail.[31m
>> [39m        on line 149 of public_html/jadu/bundles/pulsar/stylesheets/_component.block-list.scss[31m
>> [39m>>     @extend .block-list--padded;[31m
>> [39m   ----^
[33mWarning:  Use --force to continue.[39m
```

**Comment by Stanton** [comment]
Fixed and published as https://github.com/jadu/pulsar/releases/tag/6.1.2

**Comment by Stanton** [comment]
@steadweb Could you please verify?

**Comment by steadweb** [comment]
@Stanton should be fine 👍  - thanks

**Comment by steadweb** [comment]
@Stanton - `6.1` still isn't installable, although the above issue _has_ been fixed, another has occured:

```
Running "sass:dev" (sass) task
>> Error: "#pulsar .remove-button" failed to @extend ".btn--naked".
>>        The selector ".btn--naked" was not found.
>>        Use "@extend .btn--naked !optional" if the extend should be able to fail.
>>         on line 2 of public_html/jadu/bundles/pulsar/stylesheets/_component.remove-button.scss
>> >>   @extend .btn--naked;
>>    --^
Warning: Use --force to continue.
```

Would you prefer a separate issue for these, or fix them all in one go?

**Comment by Stanton** [comment]
@steadweb this ticket is fine, will be another tag

**Comment by steadweb** [comment]
Thanks. I have setup a build ready to test this out _quickly_. Although, I'm not entirely sure why this works locally... (no errors during compilation).

**Comment by steadweb** [comment]
Locally:

```
$ grunt composer
Running "copy:pulsar_dist" (copy) task
Created 207 directories, copied 1610 files
Running "sass:dev" (sass) task
Running "sass:dist_modern" (sass) task
Running "sass:dist_ie" (sass) task
Running "autoprefixer:dev" (autoprefixer) task
Running "browserify:pulsar_dist" (browserify) task
>> Bundle public_html/jadu/pulsar/js/bundle.js created.
Done, without errors.
```

**Comment by steadweb** [comment]
`~6.1.3` fixes the 2nd issue. 👍
